import type { NextPage } from "next";
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { debounce, throttle } from "../utils/Limitors";
import Nav from "../components/navigation/Nav";

const Home: NextPage = () => {
  const [mobileNavbarCollapsed, setMobileNavbarCollapsed] = useState(true);
  const [transparency, setTransparency] = useState(0.0);

  function handleScroll() {
    if (window.pageYOffset > 500) {
      setTransparency(1);
    } else {
      setTransparency(window.pageYOffset / 500.0);
    }

    setMobileNavbarCollapsed(true);
  }

  useEffect(() => {
    window.addEventListener("scroll", throttle(debounce(handleScroll)));
    return () =>
      window.removeEventListener("scroll", throttle(debounce(handleScroll)));
  }, []);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={`bg-[url('/blackbg1.svg')] min-h-[1024px] bg-fixed bg-center bg-no-repeat bg-cover text-white relative`}
      >
        <div
          style={
            mobileNavbarCollapsed
              ? {
                  backdropFilter: `blur(${transparency * 1.05}px)`,
                }
              : {
                  backdropFilter: `blur(${transparency * 1.05}px)`,
                }
          }
          className="min-h-[1024px] w-full absolute top-0 left-0"
        ></div>
        <div className="container relative">
          <Nav></Nav>
          <section className="hero-section w-[70%] mt-[115.5px] relative">
            <h1 className="text-[45px] font-medium text-white opacity-50 mb-[12px]">
              Frontend Developer
            </h1>
            <h1 className="text-[50px] font-medium text-white">
              Turning Designs to Reality
            </h1>
          </section>
        </div>
        <div className="h-[348.15px] w-[648px] hero-img absolute top-[41.5%] right-[18%] z-10">
          <Image
            className="w-full h-full object-contain"
            src={"/rectangle18.png"}
            layout="fill"
            alt="hero-img"
          />
        </div>
        <div className="absolute bottom-[11.5%] left-[11%] z-10 h-[195px]">
          <div className="h-[185px] w-[10px] hero-img">
            <Image
              className="w-full h-full object-contain"
              src={"/line.svg"}
              layout="fill"
              alt="line-img"
            />
          </div>
          <div className="mt-8 text-[20px] font-extralight">Scroll</div>
        </div>
      </main>
      <section className="skills min-h-[209px] bg-[#F4F4F4]"></section>
      <section className="about-me min-h-[630px] bg-[#F4F4F4]"></section>
      <section className="projects min-h-[581px] bg-[#070707] "></section>
      <footer
        className={`bg-[url('/blackbg2.svg')] min-h-[463px] bg-fixed bg-center bg-no-repeat bg-cover text-white flex justify-center items-center relative`}
      >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
